### ISSUE TITLE
Error: aborted due to exception java.lang.UnsupportedOperationException 

### ISSUE THREAD

**Issue by scomma** [jlewallen/jenkins-hipchat-plugin#6]
Everything goes smoothly until the plugin is triggered at the end of an otherwise successful build, then this is thrown:

```
ERROR: Publisher jenkins.plugins.hipchat.HipChatNotifier aborted due to exception
java.lang.UnsupportedOperationException
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:95)
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:59)
    at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:36)
    at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:664)
    at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:639)
    at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:617)
    at hudson.model.Build$RunnerImpl.post2(Build.java:161)
    at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:586)
    at hudson.model.Run.run(Run.java:1400)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:175)
Finished: FAILURE
```

**Comment by jonhyman** [comment]
I have the same issue.

**Comment by dhiemstra** [comment]
+1 here.

**Comment by aviks** [comment]
Any ideas on fixes or workarounds? I'm seeing the same issue. 

The write to Hipchat does happen, but as a  failure due to the exception above, even when the build is otherwise successful. 

I'm using jenkins ver 1.433 installed as  deb on ubuntu.

**Comment by scomma** [comment]
I ended up writing my own hook in bash: http://github.com/oozou/hipkins

Hope this helps.

**Comment by aviks** [comment]
Pull request with a fix: https://github.com/jlewallen/jenkins-hipchat-plugin/pull/7

**Comment by aviks** [comment]
@scomma thanks!
